### ISSUE TITLE
code style：删除废弃代码

### ISSUE THREAD

**Issue by BernieHuang2008** [OpenTeensCore/openteenscore.github.io#20]
@Nathancgy 这段代码还有用吗？如果没用就给他删了吧

https://github.com/OpenTeensCore/openteenscore.github.io/blob/ed7f37b24a3473c951f16805bf4281635ee1f3e2/css/index.css#L595-L612

**Comment by BernieHuang2008** [comment]
我觉得应该是没用的，至少我没找着在哪

**Comment by Nathancgy** [comment]
👌删了删了
